/**
 * Mock product catalog — replace fetch source in `productsApi.js` when backend is ready.
 *
 * Product shape matches expected API response so components need no changes
 * when switching from mock data to live API.
 */

/** @typedef {Object} Product
 * @property {number} id
 * @property {string} name
 * @property {string} slug
 * @property {"3D Wallpaper"|"3D Ceiling Paper"|"3D Epoxy Floor"} category
 * @property {string} roomType
 * @property {"Fabric"|"Epoxy Resin"} material
 * @property {"Matte"|"Glossy"|"Metallic"|"3D Embossed"} finish
 * @property {number} pricePerSqft
 * @property {"10 Years"|"Lifetime"} warranty
 * @property {boolean} isNew
 * @property {boolean} isBestSeller
 * @property {boolean} isFeatured
 * @property {number} rating
 * @property {number} reviewCount
 * @property {"Warm"|"Cool"|"Neutral"|"Dark"|"Light"} colorFamily
 * @property {string[]} tags
 * @property {string} image
 * @property {string} imageAlt
 * @property {string} description
 * @property {string} createdAt ISO date string
 */

export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "Royal Floral 3D Wallpaper",
    slug: "royal-floral-3d-wallpaper",
    category: "3D Wallpaper",
    roomType: "Bedroom",
    material: "Fabric",
    finish: "3D Embossed",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 186,
    colorFamily: "Warm",
    tags: ["floral", "luxury", "bedroom", "waterproof"],
    image: "/categories/wallpaper.jpg",
    imageAlt: "Royal floral 3D wallpaper in a bedroom interior",
    description:
      "Elegant floral 3D embossed wallpaper on premium waterproof fabric. Washable and tear-resistant.",
    createdAt: "2024-03-12",
    gradientFrom: "#C8956C",
    gradientTo: "#D4B896",
  },
  {
    id: 2,
    name: "Golden Damask 3D Wallpaper",
    slug: "golden-damask-3d-wallpaper",
    category: "3D Wallpaper",
    roomType: "Living Room",
    material: "Fabric",
    finish: "Metallic",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 142,
    colorFamily: "Warm",
    tags: ["classic", "luxury", "metallic", "waterproof"],
    image: "/slider-1.jpg",
    imageAlt: "Golden damask 3D wallpaper in a living room",
    description:
      "Luxurious damask pattern with metallic gold accents. Imported waterproof fabric from China.",
    createdAt: "2024-02-08",
    gradientFrom: "#C8956C",
    gradientTo: "#D4B896",
  },
  {
    id: 3,
    name: "Tropical Leaf 3D Wallpaper",
    slug: "tropical-leaf-3d-wallpaper",
    category: "3D Wallpaper",
    roomType: "Kids Room",
    material: "Fabric",
    finish: "Matte",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 89,
    colorFamily: "Cool",
    tags: ["nature", "kids", "modern", "waterproof"],
    image: "/categories/kids.jpg",
    imageAlt: "Tropical leaf 3D wallpaper in a kids room",
    description:
      "Vibrant tropical leaf design perfect for kids rooms and play areas. Easy to clean with soap and water.",
    createdAt: "2025-01-20",
    gradientFrom: "#4A7C6F",
    gradientTo: "#6A9A8A",
  },
  {
    id: 4,
    name: "Marble Effect 3D Wallpaper",
    slug: "marble-effect-3d-wallpaper",
    category: "3D Wallpaper",
    roomType: "Dining Room",
    material: "Fabric",
    finish: "Glossy",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 74,
    colorFamily: "Neutral",
    tags: ["marble", "classic", "luxury", "3d-effect"],
    image: "/slider-2.jpg",
    imageAlt: "Marble effect 3D wallpaper in a dining room",
    description:
      "Realistic marble vein texture with glossy finish. Adds sophistication to dining and living spaces.",
    createdAt: "2024-06-15",
    gradientFrom: "#FAF7F2",
    gradientTo: "#E0DDD8",
  },
  {
    id: 5,
    name: "Brick Stone 3D Panel Wallpaper",
    slug: "brick-stone-3d-panel-wallpaper",
    category: "3D Wallpaper",
    roomType: "Office",
    material: "Fabric",
    finish: "3D Embossed",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 112,
    colorFamily: "Dark",
    tags: ["3d-effect", "modern", "classic", "waterproof"],
    image: "/categories/office.jpg",
    imageAlt: "Brick stone 3D panel wallpaper in an office",
    description:
      "Industrial brick stone 3D panel effect. Ideal for accent walls in offices and commercial spaces.",
    createdAt: "2024-04-22",
    gradientFrom: "#2C2C2C",
    gradientTo: "#4A4A4A",
  },
  {
    id: 6,
    name: "Nature Forest 3D Wallpaper",
    slug: "nature-forest-3d-wallpaper",
    category: "3D Wallpaper",
    roomType: "Any Room",
    material: "Fabric",
    finish: "Matte",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 58,
    colorFamily: "Cool",
    tags: ["nature", "modern", "waterproof", "abstract"],
    image: "/categories/bedroom.jpg",
    imageAlt: "Nature forest 3D wallpaper in a bedroom",
    description:
      "Serene forest landscape with depth illusion. Brings natural calm to any room in your home.",
    createdAt: "2025-02-10",
    gradientFrom: "#4A7C6F",
    gradientTo: "#6A9A8A",
  },
  {
    id: 7,
    name: "Cloud Dream Ceiling Paper",
    slug: "cloud-dream-ceiling-paper",
    category: "3D Ceiling Paper",
    roomType: "Bedroom",
    material: "Fabric",
    finish: "Matte",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 134,
    colorFamily: "Light",
    tags: ["abstract", "bedroom", "light", "waterproof"],
    image: "/categories/celingpaper.jpg",
    imageAlt: "Cloud dream 3D ceiling paper in a bedroom",
    description:
      "Soft cloud pattern ceiling paper with lightweight ceiling-safe adhesive. Creates a dreamy bedroom atmosphere.",
    createdAt: "2025-01-05",
    gradientFrom: "#FAF7F2",
    gradientTo: "#E0DDD8",
  },
  {
    id: 8,
    name: "Golden Mandala Ceiling Paper",
    slug: "golden-mandala-ceiling-paper",
    category: "3D Ceiling Paper",
    roomType: "Living Room",
    material: "Fabric",
    finish: "Metallic",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 98,
    colorFamily: "Warm",
    tags: ["luxury", "classic", "3d-effect", "metallic"],
    image: "/slider-3.jpg",
    imageAlt: "Golden mandala ceiling paper in a living room",
    description:
      "Intricate golden mandala design for statement ceilings. Same premium fabric quality as our wallpapers.",
    createdAt: "2024-05-18",
    gradientFrom: "#C8956C",
    gradientTo: "#D4B896",
  },
  {
    id: 9,
    name: "Starlight Ceiling Paper",
    slug: "starlight-ceiling-paper",
    category: "3D Ceiling Paper",
    roomType: "Kids Room",
    material: "Fabric",
    finish: "Glossy",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 67,
    colorFamily: "Dark",
    tags: ["kids", "abstract", "3d-effect", "modern"],
    image: "/categories/kids.jpg",
    imageAlt: "Starlight ceiling paper in a kids room",
    description:
      "Glowing starlight pattern loved by children. Washable, tear-resistant ceiling-safe fabric.",
    createdAt: "2025-02-01",
    gradientFrom: "#2C2C2C",
    gradientTo: "#4A4A4A",
  },
  {
    id: 10,
    name: "Floral Crown Ceiling Paper",
    slug: "floral-crown-ceiling-paper",
    category: "3D Ceiling Paper",
    roomType: "Dining Room",
    material: "Fabric",
    finish: "3D Embossed",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 52,
    colorFamily: "Warm",
    tags: ["floral", "luxury", "classic", "waterproof"],
    image: "/categories/bedroom.jpg",
    imageAlt: "Floral crown ceiling paper in a dining area",
    description:
      "Ornate floral crown motif for elegant dining rooms. 10-year warranty on all ceiling papers.",
    createdAt: "2024-07-30",
    gradientFrom: "#C8956C",
    gradientTo: "#D4B896",
  },
  {
    id: 11,
    name: "Aurora Borealis Ceiling Paper",
    slug: "aurora-borealis-ceiling-paper",
    category: "3D Ceiling Paper",
    roomType: "Office",
    material: "Fabric",
    finish: "Glossy",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 41,
    colorFamily: "Cool",
    tags: ["abstract", "cool", "modern", "3d-effect"],
    image: "/categories/office.jpg",
    imageAlt: "Aurora borealis ceiling paper in an office",
    description:
      "Northern lights inspired ceiling design. Professional finish for modern office interiors.",
    createdAt: "2024-09-12",
    gradientFrom: "#4A7C6F",
    gradientTo: "#6A9A8A",
  },
  {
    id: 12,
    name: "Sky Blue Heaven Ceiling Paper",
    slug: "sky-blue-heaven-ceiling-paper",
    category: "3D Ceiling Paper",
    roomType: "Any Room",
    material: "Fabric",
    finish: "Matte",
    pricePerSqft: 140,
    warranty: "10 Years",
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 88,
    colorFamily: "Cool",
    tags: ["cool", "modern", "waterproof", "abstract"],
    image: "/categories/celingpaper.jpg",
    imageAlt: "Sky blue heaven ceiling paper installation",
    description:
      "Open sky blue ceiling design that makes rooms feel larger and brighter. China-imported fabric.",
    createdAt: "2024-01-25",
    gradientFrom: "#4A7C6F",
    gradientTo: "#6A9A8A",
  },
  {
    id: 13,
    name: "Ocean Blue Epoxy Floor",
    slug: "ocean-blue-epoxy-floor",
    category: "3D Epoxy Floor",
    roomType: "Kitchen",
    material: "Epoxy Resin",
    finish: "Glossy",
    pricePerSqft: 450,
    warranty: "Lifetime",
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 203,
    colorFamily: "Cool",
    tags: ["marble", "modern", "waterproof", "luxury"],
    image: "/categories/floor.jpg",
    imageAlt: "Ocean blue 3D epoxy floor in a kitchen",
    description:
      "Stunning ocean wave epoxy finish. Twice as strong as tiles, seamless with no joints. Lifetime guarantee.",
    createdAt: "2024-02-14",
    gradientFrom: "#4A7C6F",
    gradientTo: "#6A9A8A",
  },
  {
    id: 14,
    name: "Marble White Epoxy Floor",
    slug: "marble-white-epoxy-floor",
    category: "3D Epoxy Floor",
    roomType: "Living Room",
    material: "Epoxy Resin",
    finish: "Glossy",
    pricePerSqft: 450,
    warranty: "Lifetime",
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 167,
    colorFamily: "Light",
    tags: ["marble", "classic", "luxury", "modern"],
    image: "/slider-1.jpg",
    imageAlt: "Marble white epoxy floor in a living room",
    description:
      "Premium white marble vein epoxy floor. High-gloss mirror finish with professional-grade resin.",
    createdAt: "2024-04-05",
    gradientFrom: "#FAF7F2",
    gradientTo: "#E0DDD8",
  },
  {
    id: 15,
    name: "Galaxy Black Epoxy Floor",
    slug: "galaxy-black-epoxy-floor",
    category: "3D Epoxy Floor",
    roomType: "Bedroom",
    material: "Epoxy Resin",
    finish: "Metallic",
    pricePerSqft: 450,
    warranty: "Lifetime",
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 94,
    colorFamily: "Dark",
    tags: ["metallic", "abstract", "3d-effect", "luxury"],
    image: "/slider-2.jpg",
    imageAlt: "Galaxy black metallic epoxy floor",
    description:
      "Deep galaxy black with metallic shimmer particles. Impact resistant with lifetime guarantee.",
    createdAt: "2025-01-15",
    gradientFrom: "#2C2C2C",
    gradientTo: "#4A4A4A",
  },
  {
    id: 16,
    name: "Metallic Gold Epoxy Floor",
    slug: "metallic-gold-epoxy-floor",
    category: "3D Epoxy Floor",
    roomType: "Dining Room",
    material: "Epoxy Resin",
    finish: "Metallic",
    pricePerSqft: 450,
    warranty: "Lifetime",
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 76,
    colorFamily: "Warm",
    tags: ["metallic", "luxury", "modern", "classic"],
    image: "/slider-3.jpg",
    imageAlt: "Metallic gold epoxy floor in a dining room",
    description:
      "Luxurious metallic gold epoxy with seamless finish. Perfect for premium dining and lounge areas.",
    createdAt: "2024-08-20",
    gradientFrom: "#C8956C",
    gradientTo: "#D4B896",
  },
  {
    id: 17,
    name: "Rose Marble Epoxy Floor",
    slug: "rose-marble-epoxy-floor",
    category: "3D Epoxy Floor",
    roomType: "Any Room",
    material: "Epoxy Resin",
    finish: "Glossy",
    pricePerSqft: 450,
    warranty: "Lifetime",
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 48,
    colorFamily: "Warm",
    tags: ["marble", "luxury", "modern", "waterproof"],
    image: "/categories/floor.jpg",
    imageAlt: "Rose marble epoxy floor finish",
    description:
      "Soft rose marble epoxy with natural vein patterns. Durable, easy to clean, lifetime guaranteed.",
    createdAt: "2025-02-18",
    gradientFrom: "#C8956C",
    gradientTo: "#D4B896",
  },
  {
    id: 18,
    name: "Forest Green Epoxy Floor",
    slug: "forest-green-epoxy-floor",
    category: "3D Epoxy Floor",
    roomType: "Office",
    material: "Epoxy Resin",
    finish: "Matte",
    pricePerSqft: 450,
    warranty: "Lifetime",
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 61,
    colorFamily: "Cool",
    tags: ["nature", "modern", "waterproof", "classic"],
    image: "/categories/office.jpg",
    imageAlt: "Forest green epoxy floor in an office",
    description:
      "Rich forest green epoxy with matte professional finish. Ideal for offices and commercial showrooms.",
    createdAt: "2024-10-08",
    gradientFrom: "#4A7C6F",
    gradientTo: "#6A9A8A",
  },
];

/** @deprecated Use productsApi.getProducts() — kept for backward compatibility */
export const PRODUCTS = MOCK_PRODUCTS;
